name: Check for new releases
on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
    inputs:
      empty:
        description: "useless param"
        required: false
        default: ""

jobs:
  check-for-new-releases:
    name: Check for new releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python setup.py install
      - name: Execute Check for new releases
        run: shell-explorer check-new-releases --auth-key ${{ secrets.GH_TOKEN_FOR_SHELL_EXPLORER }}
