name: Run Shell Explorer
on:
  workflow_dispatch:
    inputs:
      new_releases:
        description: "a dictionary with a new releases: {repo-name: [release-id]}"
        required: true
        default: "{}"
      branch:
        description: "branch on which would be updated packages and shells yaml files"
        required: true
        default: "dev"
jobs:
  run_shell_explorer:
    name: run Shell Explorer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python setup.py install
      - name: Execute Shell Explorer
        run: shell-explorer explore
          --auth-key ${{ secrets.GH_TOKEN_FOR_SHELL_EXPLORER }}
          --branch ${{ github.event.inputs.branch }}
          --new-releases '${{ github.event.inputs.new_releases }}'
